### ISSUE TITLE
environment variables of current shell can't be passed to container via nerdctl run '-e' option 

### ISSUE THREAD

**Issue by sixwaaaay** [containerd/nerdctl#1487]
### Description

behaivors as follow will print `10`
```bash
export X=10
docker run -e X alpine printenv X
```
however, nothing will be printed when I use nerdctl
```bash
export X=10
nerdctl run -e X alpine printenv X
```

### Steps to reproduce the issue

1. set env var `export X=10`
2. run a container with the env var and print it in container `nerdctl run -e X alpine printenv X`

### Describe the results you received and expected

result: nothing 
expected: print 10 

### What version of nerdctl are you using?

nerdctl version: 

Client:
 Version:       v1.0.0
 OS/Arch:       linux/amd64
 Git commit:    c00780a1f5b905b09812722459c54936c9e070e6
 buildctl:
  Version:      v0.10.5
  GitCommit:    bc26045116045516ff2427201abd299043eaf8f7

Server:
 containerd:
  Version:      v1.6.9
  GitCommit:    1c90a442489720eec95342e1789ee8a5e1b9536f
 runc:
  Version:      1.1.4
  GitCommit:    v1.1.4-0-g5fd4c4d1

### Host information

OS information: 

PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

**Comment by djdongjin** [comment]
I tired this and noticed this might because the different behavior between docker and containerd:

Docker said an env without value (e.g., `-e X` vs `-e X=10`) means obtaining the value from shell: [docker](https://docs.docker.com/engine/reference/run/#env-environment-variables)

Containerd said that means unsetting the value: [nerdctl](https://github.com/containerd/nerdctl/blob/78de68a78b24afe97d07e9c9b1fccdca76c8a63d/cmd/nerdctl/run.go#L472), [containerd](https://github.com/containerd/containerd/blob/79389445c46369248cf59777d7e0a450e8e16a89/oci/spec_opts.go#L196).

Though I'm not sure if this is expected containerd behavior defined in oci. cc: @AkihiroSuda

**Comment by sixwaaaay** [comment]
This command does not seem to work for passing environment variables with multi-line text
My attempt is to use base64 encoding to convert multi-line text into a base64 text without line breaks every 76 characters, then pass it to the container and decode it in the container.
```bash
export X=`cat file | base64 -w 0` # export X=`printenv X | base64 -w 0`
nerdctl run -e X=$X alpine printenv X | base64 -d
```
I think it seems a little troubling

**Comment by liubin** [comment]
@sixwaaaay Do you want this?

```bash
root# export X="aaa
> bbb"

root# echo "$X"
aaa
bbb

root# _output/nerdctl run --rm --env X alpine printenv X
aaa
bbb
```
