### ISSUE TITLE
test-integration-docker-compatibility: switch away from `docker-compose` (v1) to `docker compose` (v2)

### ISSUE THREAD

**Issue by AkihiroSuda** [containerd/nerdctl#1577]
https://github.com/containerd/nerdctl/blob/dcb6a397e6b637d72fa80faca2b61d90f9a795d4/pkg/testutil/testutil.go#L595

**Comment by AkihiroSuda** [comment]
> @AkihiroSuda do we have existing blockers for this transition to `docker compose`(v2), or we just need to make sure all tests are passed after transition?

I don’t see any blocker

**Comment by djdongjin** [comment]
Hi @AkihiroSuda I'm working on this and would like to have your input on a question

docker compose v1 and v2 themselves have incompatible behaviors on some commands/formats, which fails some of our docker-compatibility tests after switching to v2, because I guess previously we follow the docker v1 behavior while writing these commands/tests.

My question is:
1. Should we change the v1 behavior in `nerdctl compose` to match v2 in such cases (and update tests accordingly)?
2. Or we should not change the current implementation, and instead should try best to write tests that are generic to both v1 and v2 (e.g., avoid v1/v2 incompatible behaviors). Then our tests won't fail for either v1 or v2.

Personally I would prefer 1 since compose-v2 has been released for a while, and it's difficult to keep `nerdctl compose` compatible with both v1 and v2.

But that also means we should check and only use `docker compose v2` in CI instead of falling back to v1 when v2 not there. (because it will fail anyway). Not sure if this is okay.

Thanks :)

**Comment by djdongjin** [comment]
As an example, docker compose v1 uses `_` when creating containers while v2 uses `-`.

```
    compose_up_linux_test.go:410: projectName="nerdctl-compose-test-1670887650"
    compose_up_linux_test.go:417: assertion failed: 
        Command:  /usr/bin/docker compose -p nerdctl-compose-test-1670887650 -f /tmp/nerdctl-compose-test370185716/docker-compose.yaml ps
        ExitCode: 0
        Stdout:   NAME                                       COMMAND             SERVICE             STATUS              PORTS
        nerdctl-compose-test-1670887650-orphan-1   "sleep infinity"    orphan              running             
        nerdctl-compose-test-1670887650-test-1     "sleep infinity"    test                running             
        
        Stderr:   
        
        Failures:
        Expected stdout to contain "nerdctl-compose-test-1670887650_orphan_1"
```

**Comment by AkihiroSuda** [comment]
Thanks, 1 seems good
