### ISSUE TITLE
creating a custom bridge before implicit creation of default bridge network triggers "failed to verify network settings [...] overlaps with other one"

### ISSUE THREAD

**Issue by thediveo** [containerd/nerdctl#2322]
### Description

- I'm aware of issue/discussion #1369, but this doesn't tackle the (different?) underlying condition waiting to throw up.
- for reference, the [failing Github job](https://github.com/siemens/ghostwire/actions/runs/5343439434/jobs/9686527051)

After installation of nerdctl and CNI plugins (such as in a Github runner VM) and after creating a custom network, any attempt to start a container attached to the default network fails with the error message:

```
FATA[0003] failed to verify networking settings: failed to create default network: subnet 10.4.0.0/24 overlaps with other one on this address space
```

However, then first manually creating the default network and then proceeding as before, no fatal error occurs. This seems to indicate that there might be some address assumption hardwired that doesn't necessarily hold true.

### Steps to reproduce the issue

1. make sure to delete all nerdctl-related networks, and "bridge" in particular: `nerdctl network rm bridge`.
2. `nerdctl network create test`
3. `nerdctl run -it --rm busybox`

## received

```
FATA[0003] failed to verify networking settings: failed to create default network: subnet 10.4.0.0/24 overlaps with other one on this address space
```

## expected

no fatal error, but command gets executed successfully.

### What version of nerdctl are you using?

nerdctl version v1.4.0
containerd version 1.6.21
CNI plugins version 1.3.0

### Are you using a variant of nerdctl? (e.g., Rancher Desktop)

None

### Host information

Ubuntu 22.04.02 LTS
Runner 2.305.0

**Comment by yldoge** [comment]
I think the problem is when you call `nerdctl network create` without passing `--subnet`, the `GetFreeSubnet` func will assign you subnet address starting from the default subnet address `10.4.0.0/24` (https://github1s.com/containerd/nerdctl/blob/main/pkg/netutil/netutil.go#L479-L480):
```
_, defaultSubnet, _ := net.ParseCIDR(DefaultCIDR)
subnet, err := subnetutil.GetFreeSubnet(defaultSubnet, usedSubnets)
```

Then you do `nerdctl run {...}` without passing `--network`, it will create and use the default network configs in which the subnet address is also be set to `10.0.4.0/24`, resulting in the address overlapping. (https://github1s.com/containerd/nerdctl/blob/main/pkg/netutil/netutil.go#L352-L353):
```
opts := CreateOptions{
		Name:       DefaultNetworkName,
		Driver:     DefaultNetworkName,
		Subnet:     DefaultCIDR,
		IPAMDriver: "default",
		Labels:     []string{fmt.Sprintf("%s=true", labels.NerdctlDefaultNetwork)},
	}
	_, err := e.CreateNetwork(opts)
```

where `DefaultCIDR` is:
```
DefaultCIDR        = "10.4.0.0/24"
```

Thinking about address assignment for `nerdctl network create` starting from `10.0.4.1/24` may fix the bug?

**Comment by thediveo** [comment]
This issues wasn't present in (much) older versions of nerdctl pre 1.0. I only revisited my nerdctl-related code base when Siemens open sourced the Edgeshark project, and only then noticed that my build pipelines are failing. The old behavior of nerdctl is in line with Docker behavior, which I understand nerdctl to be compatible to (at the CLI level).
