### ISSUE TITLE
Windows Test failed because buildkitd not supported

### ISSUE THREAD

**Issue by zwpaper** [containerd/nerdctl#2825]
### Description

buildkitd only supports linux and openbsd, but we have a windows test and will failed: https://github.com/containerd/nerdctl/actions/runs/7913136153/job/21600170296

maybe we could move the tests to linux or UNIX only?

is so I can submit a PR for it

### Steps to reproduce the issue

https://github.com/containerd/nerdctl/actions/runs/7913136153/job/21600170296

### Describe the results you received and expected

result: 

CI failed: https://github.com/containerd/nerdctl/actions/runs/7913136153/job/21600170296

expected:

CI passed

### What version of nerdctl are you using?

master

### Are you using a variant of nerdctl? (e.g., Rancher Desktop)

None

**Comment by profnandaa** [comment]
Will take a look at this now that `buildkitd.exe` is now being released for Windows starting from [`v0.13.0-rc2`](https://github.com/moby/buildkit/releases/tag/v0.13.0-rc2).

**Comment by iankingori** [comment]
@zwpaper there's this PR as well to enable `nerdctl build` for windows

**Comment by TBBle** [comment]
The CI failure in the issue body was in the [`TestVolumeLsFilter`](https://github.com/containerd/nerdctl/actions/runs/7913136153/job/21600170296#step:8:529) test, and was a flake, since that test doesn't normally fail. A rerun of the same build failed in [`TestRunEnv`](https://github.com/containerd/nerdctl/actions/runs/7913136153/job/21635595944#step:8:542) instead (a different flake), and a second rerun passed.

The lack of build support _skips_ the build tests on Windows, and so doesn't cause CI to fail, so this ticket is unrelated to the build support on Windows.

**Comment by apostasie** [comment]
@AkihiroSuda I think this should be closed.

As @TBBle stated, the failure was test flakyness - which are likely fixed now by #3285
