### ISSUE TITLE
Running a Windows container with --detach and --tty results in "nerdctl.exe must be absolute" error message

### ISSUE THREAD

**Issue by structurefall** [containerd/nerdctl#2966]
### Description

Trying to start a Windows container using -d and -t at the same time results in an error as follows:

```
PS C:\> C:\usr\bin\nerdctl\nerdctl.exe run -d -t mcr.microsoft.com/powershell:7.3-windowsservercore-ltsc2022
time="2024-05-03T17:58:37-07:00" level=fatal msg="\"\\\\C:\\\\usr\\\\bin\\\\nerdctl\\\\nerdctl.exe\" must be absolute"
```

I discovered this because I have a Windows Jenkins agent and I'm using their Docker plugin's ".inside()" method, which calls starts a container using `docker run -d -t <whatever>`. So far all other functionality has been perfectly Docker compatible, but I can't find a workaround for this. I initially thought the problem was with Jenkins, and the fact that I was running a symlink called "docker.exe" through the Jenkins plugin, however I've been able to consistently replicate the behavior with several different images, calling the nerdctl executable directly, as shown above. I even moved the executable to a directory with no spaces in its name just to eliminate that as a possible issue.

### Steps to reproduce the issue

1. Pull a compatible Windows image to a Windows machine
2. Do `nerdctl run -d -t <that image>`

### Describe the results you received and expected

I should be able to get a daemonized container with a TTY allocated, but instead I get the above error.

### What version of nerdctl are you using?

```
Client:
 Version:       v2.0.0-beta.5
 OS/Arch:       windows/amd64
 Git commit:    9236b9370203b7f3274ae8d1417cc6ddcbdd4511
 buildctl:
  Version:      v0.13.2
  GitCommit:    2e18d709fefdcc2db20853ee241c75b058189d39

Server:
 containerd:
  Version:      v1.7.13
  GitCommit:    7c3aca7a610df76212171d200ca3811ff6096eb8
 runc:
  Version:
```

### Are you using a variant of nerdctl? (e.g., Rancher Desktop)

None

### Host information

```
Client:
 Namespace:     default
 Debug Mode:    false

Server:
 Server Version: v1.7.13
 Storage Driver: windows
 Logging Driver: json-file
 Cgroup Driver:
 Cgroup Version:
 Plugins:
  Log: fluentd journald json-file syslog
  Storage: windows-lcow windows
 Security Options:
 Kernel Version:
 Operating System:
 OSType: windows
 Architecture:
 CPUs: 0
 Total Memory: 0B
 Name: <hostname>
 ID: <id>
```

**Comment by TinaMor** [comment]
Thanks @structurefall for raising the issue. Will look into it.

**Comment by TinaMor** [comment]
The issue is caused by prefixing "/" in the LogPath

https://github.com/containerd/containerd/blob/0de7043c3a8009c27cfce93320d76f9d408322ce/pkg/cio/io.go#L340:L342

However, on fixing this, we encounter a new error:

`time="2024-06-12T19:33:52+03:00" level=fatal msg="failed to create shim task: if using terminal, stderr must be empty: failed precondition"`

This error is caused by [microsoft/hcsshim]. In Windows, when terminal is specified, stdout and stderr are combined into a single output stream (which is connected to the container's terminal). This output stream is sent to the stdout pipe.

https://github.com/microsoft/hcsshim/blob/8beabacfc2d21767a07c20f8dd5f9f3932dbf305/cmd/containerd-shim-runhcs-v1/service_internal.go#L126:L128

In Containerd Stderr is set to a value, e.g.
```go
res = binary:///C:/_xxx_/nerdctl.exe?_NERDCTL_INTERNAL_LOGGING=C%3A%5CProgramData%5Cnerdctl%5C052055e3"
``` 

https://github.com/containerd/containerd/blob/4a18adcfca4e37e829c0d3174bd04d4cbf222f9a/pkg/cio/io.go#L298:L302

**Comment by TinaMor** [comment]
The issue is caused by prefixing "/" in the LogPath. See Containerd [pkg/cio/io.go#L340:L342](https://github.com/containerd/containerd/blob/0de7043c3a8009c27cfce93320d76f9d408322ce/pkg/cio/io.go#L340:L342)

However, on fixing this, we encounter another error:

`time="2024-06-12T19:33:52+03:00" level=fatal msg="failed to create shim task: if using terminal, stderr must be empty: failed precondition"`

This error is caused by [microsoft/hcsshim](https://github.com/microsoft/hcsshim). In Windows, when terminal is specified, stdout and stderr are combined into a single output stream (which is connected to the container's terminal). This output stream is sent to the stdout pipe.

See microsoft/hcsshim [service_internal.go#L127](https://github.com/microsoft/hcsshim/blob/8beabacfc2d21767a07c20f8dd5f9f3932dbf305/cmd/containerd-shim-runhcs-v1/service_internal.go#L127)

In Containerd Stderr is set to a value, e.g.
```go
res = binary:///C:/_xxx_/nerdctl.exe?_NERDCTL_INTERNAL_LOGGING=C%3A%5CProgramData%5Cnerdctl%5C052055e3"
``` 
See Containerd [pkg/cio/io.go#L298:L302](https://github.com/containerd/containerd/blob/4a18adcfca4e37e829c0d3174bd04d4cbf222f9a/pkg/cio/io.go#L298:L302)

**Comment by TinaMor** [comment]
> However, on fixing this, we encounter another error:
> 
> `time="2024-06-12T19:33:52+03:00" level=fatal msg="failed to create shim task: if using terminal, stderr must be empty: failed precondition"`
>
> See Containerd [pkg/cio/io.go#L298:L302](https://github.com/containerd/containerd/blob/4a18adcfca4e37e829c0d3174bd04d4cbf222f9a/pkg/cio/io.go#L298:L302)

Containerd changes: https://github.com/containerd/containerd/releases/tag/v2.0.0-rc.4
