### ISSUE TITLE
nerdctl login fails logging into repositories containing "/" in the registry URL.

### ISSUE THREAD

**Issue by vmwcberndt** [containerd/nerdctl#720]
Problem: Unable to log into a Docker repository that contains a sub-directory path in the URL. In this particular example, we utilize Artifactory and do not use sub-domains for registries. This worked via Docker previously. An error is returned stating there is an invalid URL escape.

nerdcrl version: nerdctl version 0.16.0
containerd version: containerd github.com/containerd/containerd v1.3.2-vmw
OS: macOS Big Sur 11.6
Kernel: Darwin <MACHINE_NAME> 20.6.0 Darwin Kernel Version 20.6.0: Mon Aug 30 06:12:21 PDT 2021; root:xnu-7195.141.6~3/RELEASE_X86_64 x86_64

```
user@machine keel % nerdctl login -u USERNAME -p PASSWORD 'artifactory.production.com/docker-local-example'
WARN[0000] WARNING! Using --password via the CLI is insecure. Use --password-stdin. 
ERRO[0000] failed to call tryLoginWithRegHost            error="parse \"https://artifactory.production.com%2Fdocker-local-example/v2\": invalid URL escape \"%2F\"" i=0
FATA[0000] parse "https://artifactory.production.com%2Fdocker-local-example/v2": invalid URL escape "%2F" 
```

**Comment by alisson276** [comment]
I got the same proble. I'll try to explain. If in the artifactory we access [artifactory-url.my.domain/v2](artifactory-url.my.domain/v2), it returns 404, but if I open [artifactory-url.my.domain/v2/](artifactory-url.my.domain/v2/) (pay attention to the last slash) it returns `{"errors":[{"code":"UNAUTHORIZED","message":"authentication required","detail":null}]}` (this last behavior means it works).

The problem is `nerdctl` doesn't append the last slash in the URL since version 0.16.0 (version 0.15.0 docker login works)

**Comment by AkihiroSuda** [comment]
@alisson276 Your case is different and tracked in https://github.com/containerd/nerdctl/issues/715
